image: docker:20.10.14

precommit:
  image: python:3.10.2-slim-bullseye
  before_script:
    - apt update && apt install -y --no-install-recommends git
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install pre-commit
  script:
    - pre-commit run --from-ref origin/HEAD --to-ref HEAD
